Kirill
vshat-tms/lesson16-homework pull request #4
Opened 2022-03-15 11:01 UTC by PolichF1

Add homework commands

2022-03-15 16:33 UTC, antonfcss requested changes

2022-03-15 16:33 UTC, antonfcss commented on src/main/kotlin/commands/TimerFromKirill.kt
> +                }else{
Где пробел?!?!

2022-03-15 16:33 UTC, antonfcss commented on src/main/kotlin/commands/fizzbuzzFromKirill.kt
> +        val isTrue = true
Зачем?

2022-03-15 16:33 UTC, PolichF1 commented on src/main/kotlin/commands/fizzbuzzFromKirill.kt
> +        val isTrue = true
жесть...

2022-03-16 18:06 UTC, KrasavaStep requested changes

2022-03-16 18:06 UTC, KrasavaStep commented on src/main/kotlin/commands/TimerFromKirill.kt
> +            val timerCount = if (text.isNotBlank()){
Отсутствует проверка если число не входит в диапазон 5 - 10. Также код немного не отформатирован))

2022-03-19 07:45 UTC, UlasevichVadim commented
Approve

2022-03-19 07:45 UTC, UlasevichVadim commented
Approve

2022-03-29 09:53 UTC, PetrGrebnev commented on src/main/kotlin/commands/ConvertCelsiusToFahrenheitCommand.kt
> +            val celsius = text.toDouble()
Try catch, можно обернуть только эти методы или использовать .toDoubleOrNull(), а не весь код выполнение. По всей домашки.

2022-03-31 16:52 UTC, closed without merging