Add commands Timer.kt, CelsiusToFahrenheit.kt, FahrenheitToCelsius.kt…
vshat-tms/lesson16-homework pull request #5
Opened 2022-03-15 16:28 UTC by antonfcss

2022-03-16 17:57 UTC, KrasavaStep requested changes

2022-03-16 17:57 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBuzz.kt
> +        val isTrue = true
зачем здесь константа isTrue

2022-03-16 17:57 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBuzz.kt
> +        } else (number !in 20..100)
Код в строках 32 - 39 выводит только числа от 1 до введённого, без fizz, buzz, fizzbuzz

2022-03-17 09:02 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +        val isTrue = true
Исправил) Добавил буленовское значение, чтобы в случае неправильного ввода мы могла сразу повторить ввод.

2022-03-17 09:02 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +        } else (number !in 20..100)
Исправил

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-22 16:26 UTC, vshat-tms commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        val consA = 1.8
1. name
2. `const val`

2022-03-22 16:26 UTC, vshat-tms commented on src/main/kotlin/commands/FizzBuzz.kt
> +            isCorrect=inputNumber in 20..100
`ctrl+alt+l` all your files

2022-03-23 07:06 UTC, antonfcss commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        val consA = 1.8
Исправил

2022-03-23 07:06 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +            isCorrect=inputNumber in 20..100
Исправил

2022-03-23 21:02 UTC, DmitriyGotovko requested changes

2022-03-23 21:02 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +                        else -> println(number)
3, 5, 15, 20, 100 в константы выведи

2022-03-23 21:02 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +            Thread.sleep(1000)
const

2022-03-23 21:02 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +            for (number in number downTo (1)) {
почему 1 в скобках ?

2022-03-23 21:02 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +                println("..")
почему бы в один print не внести и number и точки, хотя может уже придираюсь )

2022-03-23 21:02 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +        val number = scanner.nextInt()
обработай ввод исключением

2022-03-23 21:35 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +                        else -> println(number)
Исправил

2022-03-23 21:35 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +            Thread.sleep(1000)
Исправил

2022-03-23 21:35 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +            for (number in number downTo (1)) {
Исправил

2022-03-23 21:35 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +                println("..")
Исправил

2022-03-23 21:35 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +        val number = scanner.nextInt()
Исправил

2022-03-25 14:06 UTC, DmitriyGotovko commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        val celsius: Double
все преобразование можно сделать в try

2022-03-25 14:07 UTC, DmitriyGotovko commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        println("${String.format("%.2f", celsius)}°C = ${String.format("%.2f", fahrenheit)}℉")
19 20 строки в try, код меньше и не так разбросан

2022-03-25 14:08 UTC, DmitriyGotovko commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +            celsius = text.toDouble()
здесь сразу можно val celsius = text.toDouble(), val celsius перед try лишнее

2022-03-25 14:09 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FahrenheitToCelsius.kt
> +        val celsius = (fahrenheit - 32) / 1.8
то же что и в c_to_f

2022-03-25 14:10 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +    override val description = " FizzBuzz ᕦ(ツ)ᕤ "
укажи что делает твой код, т.е действие

2022-03-25 14:11 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +        var isCorrect = false
для чего ?

2022-03-25 14:13 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +            if (isCorrect) {
попробуй без isCorrect, 18 строку сразу в if

2022-03-25 14:14 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +                        else -> println(number)
ты как исправишь, жми кнопку снизу слева в коменте, не помню как она называется

2022-03-25 14:15 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +        val number = scanner.nextInt()
ввод в 14 строке, соответственно заверни ее в try

2022-03-25 14:16 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +                    Thread.sleep(MILLIS.toLong())
toLong не обязательно

2022-03-25 14:16 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +                    Thread.sleep(MILLIS.toLong())
toLong

2022-03-25 19:35 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +            if (isCorrect) {
> попробуй без isCorrect, 18 строку сразу в if

исправил

2022-03-25 19:35 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +        var isCorrect = false
> для чего ?
Исправил

2022-03-25 19:36 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +    override val description = " FizzBuzz ᕦ(ツ)ᕤ "
> укажи что делает твой код, т.е действие
Исправил

2022-03-25 19:36 UTC, antonfcss commented on src/main/kotlin/commands/FahrenheitToCelsius.kt
> +        val celsius = (fahrenheit - 32) / 1.8
> то же что и в c_to_f

Исправил

2022-03-25 19:36 UTC, antonfcss commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +            celsius = text.toDouble()
> здесь сразу можно val celsius = text.toDouble(), val celsius перед try лишнее

исправил

2022-03-25 19:36 UTC, antonfcss commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        println("${String.format("%.2f", celsius)}°C = ${String.format("%.2f", fahrenheit)}℉")
> 19 20 строки в try, код меньше и не так разбросан

исправил

2022-03-25 19:36 UTC, antonfcss commented on src/main/kotlin/commands/CelsiusToFahrenheit.kt
> +        val celsius: Double
> все преобразование можно сделать в try

исправил

2022-03-25 19:37 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +        val number = scanner.nextInt()
> ввод в 14 строке, соответственно заверни ее в try

Исправил

2022-03-25 19:39 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +                    Thread.sleep(MILLIS.toLong())
![image](https://user-images.githubusercontent.com/95831815/160190031-00264975-14f1-4960-b5c1-d4374e51116b.png)

2022-03-25 19:48 UTC, antonfcss commented on src/main/kotlin/commands/Timer.kt
> +                    Thread.sleep(MILLIS.toLong())
![image](https://user-images.githubusercontent.com/95831815/160191281-915741ed-da9a-4fa3-90cb-e1be71ae1623.png)

2022-03-25 19:53 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBuzz.kt
> +    override val description = " Multiplicity Check: 3, 5, 15 and replacing numbers with words"
после первой ковычки пробел лишний

2022-03-25 20:00 UTC, antonfcss commented on src/main/kotlin/commands/FizzBuzz.kt
> +    override val description = " Multiplicity Check: 3, 5, 15 and replacing numbers with words"
Исправил)))

2022-03-26 03:53 UTC, DmitriyGotovko approved these changes

2022-03-31 06:51 UTC, antonfcss commented
Исправлены все моменты обсуждаемые на прошлом уроке (отступы, создан метод отдельный для подсчёта)

2022-03-31 16:54 UTC, closed without merging