Add Timer, F_To_C, C_To_F, FizzBuzz
vshat-tms/lesson16-homework pull request #6
Opened 2022-03-16 17:12 UTC by PetrGrebnev

2022-03-16 18:02 UTC, KrasavaStep requested changes

2022-03-16 18:02 UTC, KrasavaStep commented on src/main/kotlin/commands/Timer.kt
> +        if (num in 5..10) run(num)
отсутствует ветка else если число вне диапазона 5 - 10

2022-03-16 18:09 UTC, PetrGrebnev commented on src/main/kotlin/commands/Timer.kt
> +        if (num in 5..10) run(num)
Спасибо, не заметил
уже исправил

2022-03-17 19:41 UTC, GansA11es commented on src/main/kotlin/commands/Timer.kt
> +    private fun run(num: Int = 5) {
сделай более понятным название функции

2022-03-17 19:41 UTC, GansA11es commented on src/main/kotlin/Main.kt
> +    FizzBuzz()
Измени название классов

2022-03-17 19:42 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBuzz.kt
> +            var nummber = text.toInt()
очепятка в nummber)

2022-03-17 19:42 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBuzz.kt
> +                for (num in 1..nummber) {
в форе лучше использовать i

2022-03-17 19:42 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBuzz.kt
> +                    when {
можно присвоить when перемнной и сделать так чтобы вызвать println 1 раз

2022-03-17 19:42 UTC, KrasavaStep commented on src/main/kotlin/commands/Timer.kt
> +        if (num in 5..10) run(num)
имя функции run лучше поменять на более содержвательное

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-22 16:23 UTC, vshat-tms commented on src/main/kotlin/commands/FahrenheitToCelsiusCommand.kt
> +            fahrenheit = text.toDoubleOrNull()!!
toDouble()

2022-03-22 19:52 UTC, PetrGrebnev commented on src/main/kotlin/commands/FahrenheitToCelsiusCommand.kt
> +            fahrenheit = text.toDoubleOrNull()!!
done

2022-03-22 21:01 UTC, vshat-tms commented on src/main/kotlin/commands/TimerCommand.kt
> +            startedTimer()
startTimer

2022-03-22 21:03 UTC, closed without merging