add my commands and change Main
vshat-tms/lesson16-homework pull request #7
Opened 2022-03-16 17:12 UTC by GansA11es

2022-03-16 18:09 UTC, KrasavaStep requested changes

2022-03-16 18:09 UTC, KrasavaStep commented on src/main/kotlin/commands/Sib_timer.kt
> +            val timeValue = if (text.isNotBlank())
Отсутствует проверка есть ли число в диапазоне 5 - 10

2022-03-16 18:34 UTC, GansA11es commented on src/main/kotlin/commands/Sib_timer.kt
> +            val timeValue = if (text.isNotBlank())
исправлено

2022-03-17 19:39 UTC, KrasavaStep commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +        try {
try должен быть обёрнут вокруг кода где возможна ошибка т.е. только вокруг val celIn = text.toDouble

2022-03-17 19:39 UTC, KrasavaStep commented on src/main/kotlin/commands/Sib_timer.kt
> +            val timeValue = if (text.isNotBlank() && text.toInt() in 5..10)
лучше разделить на несколько блоков кода для лучшей читабельности и если в if происходит действие - обернуть в фигурные скобки

2022-03-17 19:39 UTC, KrasavaStep commented on src/main/kotlin/commands/Sib_timer.kt
> +        catch (ex: Exception){
Exception - ловит все исключения, нужно поставить какой-то конкретный Exception

2022-03-17 19:41 UTC, PetrGrebnev commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +class Sib_C_to_F: Command {
что значит название класса?

2022-03-17 19:41 UTC, PetrGrebnev commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +        } catch (ex: Exception) {
какой Exception отлавливает этот catch?

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-19 12:31 UTC, GansA11es commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +        } catch (ex: Exception) {
Код исправлен, try catch не используется

2022-03-19 12:31 UTC, GansA11es commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +class Sib_C_to_F: Command {
Названия классов изменены

2022-03-19 12:32 UTC, GansA11es commented on src/main/kotlin/commands/Sib_timer.kt
> +        catch (ex: Exception){
Код исправлен, try catch не используется

2022-03-19 12:32 UTC, GansA11es commented on src/main/kotlin/commands/Sib_timer.kt
> +            val timeValue = if (text.isNotBlank() && text.toInt() in 5..10)
Исправлено ( теперь используется toIntOrNull)

2022-03-19 12:33 UTC, GansA11es commented on src/main/kotlin/commands/Sib_C_to_F.kt
> +        try {
Код исправлен, try catch не используется

2022-03-22 16:16 UTC, vshat-tms commented
Approved

2022-03-22 16:16 UTC, closed without merging