CommandsFromDmitrijGotovko
vshat-tms/lesson16-homework pull request #8
Opened 2022-03-17 00:03 UTC by DmitriyGotovko

2022-03-17 19:36 UTC, KrasavaStep commented on src/main/kotlin/commands/C_to_f.kt
> +class C_to_f(){
Имя класса должно быть содержательным и быть в виде глагола

2022-03-17 19:36 UTC, KrasavaStep commented on src/main/kotlin/commands/FizzBazz.kt
> +        try {
try должен быть обёрнут только вокруг того кода где возможна ошибка

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-19 07:46 UTC, UlasevichVadim commented
Approve

2022-03-22 16:11 UTC, vshat-tms commented on src/main/kotlin/commands/FizzBazz.kt
> +        }catch (e: NumberFormatException) {
1

2022-03-22 16:14 UTC, vshat-tms requested changes

2022-03-22 16:14 UTC, vshat-tms commented on src/main/kotlin/commands/Timer.kt
> +    override val keyword: String = "timer "
1

2022-03-22 16:14 UTC, vshat-tms commented on src/main/kotlin/commands/Timer.kt
> +                for (i in inputValue downTo 1) {
5,10, 1000 to const

2022-03-22 16:14 UTC, vshat-tms commented on src/main/kotlin/commands/HelloFromDmitrij.kt
> +    override val description = "Hello! I'm Dima"
1

2022-03-23 04:07 UTC, DmitriyGotovko commented on src/main/kotlin/commands/C_to_f.kt
> +class C_to_f(){
да, конечно

2022-03-23 04:07 UTC, DmitriyGotovko commented on src/main/kotlin/commands/FizzBazz.kt
> +        try {
try у меня перед вводом, чтобы отслеживать неправильность ввода, получается catch сразу после ввода?

2022-03-23 04:07 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +                for (i in inputValue downTo 1) {
исправил

2022-03-23 06:39 UTC, VovoZozo commented on src/main/kotlin/commands/Timer.kt
> +                for (i in inputValue downTo 1) {
5,10,1000Не вынесены в константы

2022-03-23 17:55 UTC, PetrGrebnev commented on src/main/kotlin/commands/Timer.kt
> +            } else {
При выполнение else будет выведен 0 два раза

2022-03-23 18:40 UTC, DmitriyGotovko commented on src/main/kotlin/commands/Timer.kt
> +            } else {
согласен фор до 1 сделаю

2022-03-23 19:09 UTC, PetrGrebnev commented
Approve

2022-03-24 16:09 UTC, closed without merging